### ISSUE TITLE
Lazarus Rework

### ISSUE THREAD

**Issue by BoNT325** [Kohan-Citadel/kohangold-KG-#102]
[ObjectData]
430HP 
DV 8

Spell0 = Shadow Blessing
Spell1 = Lethargy

[Level1]
HP 560 
DV 10

Spell0 = Shadow Blessing
Spell1 = Lethargy

[ElementBonus1]
ATTACK_BONUS_TO_NONSHADOW = 2

[SupportBonus1]
REVERSE_DAMAGE_WHEN_HIT = 2

[Level2]
HP690 
DV 10

Spell0 = Shadow Blessing
Spell1 = Acolyte's Vulnerability

[ElementBonus2]
ATTACK_BONUS_TO_NONSHADOW = 4

[SupportBonus2]
REVERSE_DAMAGE_WHEN_HIT = 4

HP820 
DV 10

Spell0 = Shadow Blessing
Spell1 = Acolyte's Vulnerability

[ElementBonus3]
ATTACK_BONUS_TO_NONSHADOW = 6

[SupportBonus3]
MELEE_UNHOLY_DAMAGE = 2
REVERSE_DAMAGE_WHEN_HIT = 6

**Comment by sceadu37** [comment]
Adding.  Going to give him Vulnerability instead of the dummy spell, as I assume that was the intention
