### ISSUE TITLE
Praxus Rework

### ISSUE THREAD

**Issue by BoNT325** [Kohan-Citadel/kohangold-KG-#104]
HP 400 
DV8
AV 32 
Maxmana = 60 
ManaRegenerationRate = 4

Spell0 = Lightning
Spell1 = Mystic Shield

[SupportBonus]
ZONE_OF_CONTROL_BONUS = 1.10

[Level1]
HP500 
DV8
AV36
Maxmana = 70 
ManaRegenerationRate = 6 

Spell0 = Lightning
Spell1 = Mystic Shield

[SupportBonus1]
ZONE_OF_CONTROL_BONUS = 1.2

[Level2]
HP600 
DV8
AV38

Maxmana = 70 
ManaRegenerationRate = 6 

Spell0 = Forked Lightning
Spell1 = Mystic Barrier

[SupportBonus2]
ZONE_OF_CONTROL_BONUS = 1.25

[Level3]
HP 700 
DV 10
AV 40
Maxmana = 70  
ManaRegenerationRate = 8

Spell0 = Forked Lightning
Spell1 = Mystic Barrier

[ElementBonus3]
DAMAGE_TAKEN_FROM_MELEE = 0.75

[SupportBonus3]
ZONE_OF_CONTROL_BONUS = 1.25

**Comment by sceadu37** [comment]
adding
