### ISSUE TITLE
Sarai Marusek Rework

### ISSUE THREAD

**Issue by BoNT325** [Kohan-Citadel/kohangold-KG-#107]
HP 430 
DV 8
AV 34

MaxMana = 60
ManaRegenerationRate = 4

Spell0 = Protection
Spell1 = Recovery

[SupportBonus]
DAMAGE_TAKEN_FROM_UNHOLY = 0.75

[Level1]
HP520 
DV8
AV 38

Spell0 = Protection
Spell1 = Recovery

[SupportBonus1]
ATTACK_BONUS_TO_SHADOW = 2
DAMAGE_TAKEN_FROM_UNHOLY = 0.75

[Level2]
HP 610 
DV 8
AV40

Spell0 = Protection
Spell1 = Renewal

[SupportBonus2]
MORALE_LOSS_RATE_BONUS = 0.9
ATTACK_BONUS_TO_ANY = 2
ATTACK_BONUS_TO_SHADOW = 3
DAMAGE_TAKEN_FROM_UNHOLY = 0.75

[Level3]
HP700 
DV 8
AV 42

Spell0 = Protection
Spell1 = Renewal

[SupportBonus3]
MORALE_LOSS_RATE_BONUS = 0.8
ATTACK_BONUS_TO_ANY = 4
ATTACK_BONUS_TO_SHADOW = 4
DAMAGE_TAKEN_FROM_UNHOLY = 0.75

**Comment by sceadu37** [comment]
Adding
