### ISSUE TITLE
Tech: Rename Magic Arrow to Maecyne Arrow

### ISSUE THREAD

**Issue by BoNT325** [Kohan-Citadel/kohangold-KG-#218]
As per the Quest for Darius opening, giving it its proper name.

**Comment by sceadu37** [comment]
@BoNT325 do you want to update the description of the tech as well? Could do something like:
"These arrow heads are forged in the likeness of an ancient relic, making them capable of inflicting magical damage upon their targets."
[Quest for Darius Into Transcript.txt](https://github.com/Kohan-Citadel/kohangold-KG-/files/13290038/Quest.for.Darius.Into.Transcript.txt)
