### ISSUE TITLE
Unit: Golem

### ISSUE THREAD

**Issue by Flukenstein** [Kohan-Citadel/kohangold-KG-#226]
Fun concept 
loses games more often than not, Very expensive to field short (40G + captain)
Has tech potential with kohan buffs and provided modifiers.
unlimited morale is always handy, vulnerable to enchantments but could soak DPS from range quite well.

Very slow. 14 MS. MS
average DV mandatory being a "weaker elemental"

Adjustments
Unit Cost 10 - > 8 (already expensive upkeep)
Movementspeed  14 - > 15

**Comment by sceadu37** [comment]
An interesting note, golems don't have a listed commission cost. 10 is the default value assigned to any unit missing CostGold in its INI

**Comment by Flukenstein** [comment]
huh, wasn't aware of that
