### ISSUE TITLE
Unit: Pikeman adjustment

### ISSUE THREAD

**Issue by Flukenstein** [Kohan-Citadel/kohangold-KG-#227]
(Work in progress)

This unit is a powerhouse, scales great with other tech units and is generally way too good
At it's job for price.
Considering the reduction from billet roy are particularly brutal at abusing this company.
They also are very rewarding to be kept alive.

Need some information on their unit groups and what's applying to them currently.
assuming very little affects them.
Nerf stick needed.

Movement Speed 20 - > 16 to reflect their Heavy armor.
This unit is the cheapest 14 DV unit you could possibly hope for.
They also have 2 greater damage, and is functionally a massive upgrade over footmen
barring some extreme techs on the footmen.

**Comment by sceadu37** [comment]
Pikemen and Footmen are in the same unit groupings, so they should all benefit from the same set of techs
