### ISSUE TITLE
[Misc] Standardize Folder Name Case

### ISSUE THREAD

**Issue by sceadu37** [Kohan-Citadel/kohangold-KG-#285]
We've ended up with EffectData and EFFECTDATA as separate folders in the repo, with many of the other files and folders being split between the two cases. While it doesn't cause problems per se (the folders are merged when pulled locally), it is messy and throws off unsophisticated autocomplete. 
I would vote to capitalize everything, as this is consistent with the original file and folder names.

**Comment by sceadu37** [comment]
I've been thinking about this a bit more, and sticking to camel case for folders and uppercase w/ underscores for files might be the most readable, so TGXFiles/Data/SPELLS_KE.INI for example, or TGXFiles/Data/ObjectData/Heroes/THORA_MAESUN.INI

**Comment by BoNT325** [comment]
So this is a lot easier said than done, and runs the risk of git not recognising files as the same entity and instead as totally new files. Not impossible and not a bad idea, but can very easily go wrong. You're welcome to change the capitalisation on your local folders if it makes it easier to read until I look into this a little more. For now I'm extremely wary of merging any changes that could potentially break the commit history on individual files.

**Comment by sceadu37** [comment]
I did a little more testing, and while git does recognize that they are the same files (rename rather than add/delete), it's still probably a no-go, because git displays a link to commit history under the previous name, rather than just displaying it.
![image](https://github.com/Kohan-Citadel/kohangold-KG-/assets/44327463/5fbd0229-aac6-4450-a69d-6a382a36f84f)
All the data is still there, BUT having to click into a separate screen to most of the file history doesn't seem worth it
