### ISSUE TITLE
Various hero updates.

### ISSUE THREAD

**Issue by Flukenstein** [Kohan-Citadel/kohangold-KG-#293]
- [x] #296

mana returned to 60 at awake.
or increase aoe to 1.5. (shadow stun)

- [x] #297
Cold Snap 35 to > 30 mana.

- [x] #298
Attack backswing balanced to attack rate. (nerf)

- [x] #299
Balance Backswing to attack rate.(nerf)

- [x] #300
Adjust Illyana's backswing to be match her attack rate* (buff)

- [x] #301
DV at all levels 14! (compensating for immortal fury isn't too important he ends up outscaling the penalty with company exp)
Hp at ascended 1200 even (20 more)

- [x] #302
Attack bonus vs shadow 3 > 3 > 4 > 4 (provided)

- [x] #303
+50 HP at all levels

- [x] #304
Remove battle chant from Ruarc +1 DV removed. (filler spell to be upgraded to spirit of battle, wasted somewhat with his strong melee stats and cast time)

Frenzy/Bloody Frenzy remove self damage component

**Comment by Flukenstein** [comment]
Just suggestions**  up for discussion

**Comment by Flukenstein** [comment]
Hunter's range makes him the first to be targeted by spells and archers from enemy ranged.
(When they reaquire from killing a target they will target the closest aka the hunter if range v range)
Intention was that he'd sit behind a frontline of scouts/other melee companies such as super scouts super lancers, paladins etc.
however this isn't entirely obvious to everyone.

**Comment by sceadu37** [comment]
Just a note on Frenzy: I couldn't figure out how to make a self-targeting spell deal damage, so Frenzy has never dealt damage to the caster
