### ISSUE TITLE
Increase formation modifier for Building

### ISSUE THREAD

**Issue by sceadu37** [Kohan-Citadel/kohangold-KG-#331]
Change Building formation AV modifier from 25% to 50%, so engineers don't automatically lose to everything if interrupted mid-construction.

**Comment by BoNT325** [comment]
I'm going to change the rate that AV drops from 2 to 1 as well, so it's a more steady decrease in fighting efficiency. Column and pressed formation drop at 2 and 3 respectively, but that makes more sense as it's a marching formation and forced march respectively. I can imagine engineers being dedicated to construction being taken by surprise by attackers, but they would not be as exhausted/unprepared as if they were focused on marching at full speed.
