### ISSUE TITLE
[Tech] Slaanri Champion & Slaanri Spears

### ISSUE THREAD

**Issue by sceadu37** [Kohan-Citadel/kohangold-KG-#380]
+AV techs do not tend to be very interesting, so combine Slaanri Spears and Slaanri Champion into a new tech. If the champions are feeling too strong with the guaranteed +2AV, consider reducing their AV by 1 to 27, (they will reach the same AV at elite as they would with 28AV and no bonus).
Two possible names are "Slaanri Allies" and "Slaanri Auxiliaries", with a description along these lines:
"The Slaanri Champions are the strongest and deadliest of the Slaanri warriors. In honor of their powerful and violent cousins, the Slaanri champions wield forked bone spears in combat. They have taught the construction technique of these fearsome weapons, allowing for the creation of more effective arms for spear wielding troops."

Both techs in question are critical to The Enemy Within campaign, so both should be set to Boss=1 rather than being overwritten.

**Comment by sceadu37** [comment]
As it turns out, only one technology can give access to a unit, so the above approach will not work. We will need to:
* either make a duplicate Slaanri Champion for MP;
* or give the combined tech in the campaign when you would normally only get the champion
* or decide not to go forward with the change

**Comment by BoNT325** [comment]
For multiple campaign balance purposes, the techs cannot be combined. Some adjustments can be done but no combinations. Closing this as not planned, the issues with either techs can be raised separately.

**Comment by sceadu37** [comment]
Agreed, any changes here need to not interfere with The Enemy within.
Slaanri Spears is given at the beginning of Mission 1, so that tech should be left unchanged and set to Boss=1
The hope was to set Slaanri Champion to Boss=1 as well, and have a MP-only tech combining the two. However, due to limitations described above that approach isn't possible.
I think the most workable solution is to leave Slaanri Champion as Boss=0 and edit it to include a +2AV bonus for Group 7. The Slaanri Champion unit can then be adjusted to have 1 less AV to somewhat counteract the guaranteed bonus (they will reach the same elite AV as before). The only unit in The Enemy Within that will benefit from what is essentially two copies of Slaanri Spears is the Slaanri Captain. If this feels like an issue, we can definitely workshop other potential solutions (one is creating a MP slaanri champion unit, which is mechanically the cleanest but also wasteful of limited resources; another is giving the player a dummy tech that reduces group 7 AV at the same time as giving the bundled slaanri champion, so that the overall AV of group 7 units will be identical to what it would be pre-change).
I'd like to discuss this further to see if a viable solution can be found.
